# Docker Compose 配置 - 鲲鹏煎药管理控制系统
version: '3.8'

services:
  # Nginx Web服务器
  nginx:
    image: nginx:alpine
    container_name: kunpeng-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx-docker.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - kunpeng-network

  # Node.js应用服务器（可选，如果需要SSR）
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kunpeng-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://192.168.80.75:8000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - kunpeng-network

networks:
  kunpeng-network:
    driver: bridge

volumes:
  logs:
